name: Ceramic_Segmentation

dependencies:
  - python=3.7
  - tensorflow
  - jupyter
  - numpy
  - matplotlib
  - pandas
  - scipy
  - pydot 
  - opencv
  - pip
  - pylint
  - graphviz 
  - pip:
    - segmentation-models




